### ISSUE TITLE
Missing FindZeroMQ.cmake

### ISSUE THREAD

**Issue by smeckels** [zeromq/cppzmq#127]
Attempting to build on Ubuntu 16.04 after installing ZeroMQ 4.2.1

> CMake Error at CMakeLists.txt:4 (find_package):
>   By not providing "FindZeroMQ.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "ZeroMQ", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "ZeroMQ" with any
>   of the following names:
> 
>     ZeroMQConfig.cmake
>     zeromq-config.cmake
> 
>   Add the installation prefix of "ZeroMQ" to CMAKE_PREFIX_PATH or set
>   "ZeroMQ_DIR" to a directory containing one of the above files.  If "ZeroMQ"
>   provides a separate development package or SDK, be sure it has been
>   installed.

> -- Configuring incomplete, errors occurred!

Am i invoking cmake incorrectly?

**Comment by z3t0** [comment]
@smeckels Place [this](https://gist.github.com/z3t0/2c1c3fad2aeb65f10146fbc74a758d8a) somewhere in CMAKE_MODULE_PATH

**Comment by z3t0** [comment]
Or [this](https://raw.githubusercontent.com/Kitware/Remus/master/CMake/FindZeroMQ.cmake) actually seems much more complete. 

Though this requires you to comment lines 6-7 in CMakeLists.txt for this library

**Comment by stevemk14ebr** [comment]
Thank you. I've submitted a PR based on your solution, it does work well.

**Comment by z3t0** [comment]
Just to be clear though this is what worked for me and I am not sure if commenting those 3 lines will have any other adverse side effects.

**Comment by ax3l** [comment]
this should be fixed in the 4.2.2 release as of #133

**Comment by Zvax** [comment]
I just got the same error from both downloading the 4.2.2 tar.gz file from the releases and checking out master. Being fairly new with cmake I'm not sure what I should include, but [here](https://gist.github.com/Zvax/f076f961fa9b27599aa198e69096b3e3) is the CMakeOutput.log and the error (which seems to be exactly the same as OP).

> CMake Warning at CMakeLists.txt:4 (find_package):
>   By not providing "FindZeroMQ.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "ZeroMQ", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "ZeroMQ" with any
>   of the following names:
> 
>     ZeroMQConfig.cmake
>     zeromq-config.cmake
> 
>   Add the installation prefix of "ZeroMQ" to CMAKE_PREFIX_PATH or set
>   "ZeroMQ_DIR" to a directory containing one of the above files.  If "ZeroMQ"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> CMake Error at CMakeLists.txt:12 (message):
>   ZeroMQ was NOT found!
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/zvax/library/cppzmq-4.2.2/build/CMakeFiles/CMakeOutput.log".

I'll try with @z3t0's suggestions, but just thought maybe I should report this.

**Comment by ax3l** [comment]
@Zvax first you need to install [libzmq](https://github.com/zeromq/libzmq) itself.

If `libzmq` is not installed in a system location, but a user-defined location `$LIBZMQ_PREFIX` you will need to set environment hints before installing `cppzmq`.

If you install `libzmq` via its CMake install, extend the environment variable `CMAKE_MODULE_PATH` with its install prefix:
```bash
export CMAKE_MODULE_PATH=$LIBZMQ_PREFIX:$CMAKE_MODULE_PATH
```

Alternatively, if you install `libzmq` via autotools, extent the paths in `PKG_CONFIG_PATH`:
```bash
export PKG_CONFIG_PATH=$LIBZMQ_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH
```

**Comment by Zvax** [comment]
Wow... Indeed, as instructed in the README, one should install libzmq first. I'm not sure how, but I think I figured this was all in that same repository, despite being named differently and all... Sorry for your time, and thanks for that.

For the next absolute beginner that comes here, could you maybe consider merging a pull request that adds a link towards the libzmq github project in this one's README?

https://github.com/zeromq/cppzmq/pull/164

**Comment by karmux** [comment]
I have "FindZeroMQ.cmake" in CMAKE_MODULE_PATH but it still doesn't find it.

`MESSAGE(STATUS CMAKE_MODULE_PATH:${CMAKE_MODULE_PATH})`
prints
`-- CMAKE_MODULE_PATH:/opt/foo/cmake`

```
# ls -l /opt/foo/cmake/FindZeroMQ.cmake
-rw-r--r-- 1 1000 1000 441 Mar 30 10:32 /opt/foo/cmake/FindZeroMQ.cmake
```

**Comment by ax3l** [comment]
You don't need FindZeroMQ.cmake anymore. Just extend the paths as posted two post above :)

**Comment by sigiesec** [comment]
@ax3l I am not sure what you mean by "anymore". I have recently added CI for cppzmq. If you can send a PR that removes it and the tests and demo are still working, then maybe this might simplify things.

**Comment by ax3l** [comment]
After we implemented  #133 it does not matter anymore if you installed `libzmq` via cmake or autotools.

Assume `libzmq` is installed in `$LIBZMQ_PREFIX`.
If you want to build `cppzmq` on top of it, just run

```bash
export CMAKE_PREFIX_PATH=$LIBZMQ_PREFIX:$CMAKE_PREFIX_PATH

cmake ..
make install
```

or in the [autotools `libzmq` case](https://github.com/zeromq/cppzmq/pull/133#issuecomment-315686690)

```bash
export PKG_CONFIG_PATH=$LIBZMQ_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH

cmake ..
make install
```

to install `cppzmq`.

**Comment by ax3l** [comment]
Oh, I just see that you refactored `libzmqPkgConfigFallback.cmake` into a `FindZeroMQ.cmake` since then...

**Comment by ax3l** [comment]
I think one can close this issue and open new ones for new reports.

Not sure what version @karmux is referring to, but the questions above where pre- #133 related

**Comment by karmux** [comment]
I was trying to find my own `FindZeroMQ.cmake` but had missing `CMAKE_ARGS -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}` for `ExternalProject_Add`.

As @axel suggested I deleted my own `FindZeroMQ.cmake` since ZeroMQ (libzmq) has `ZeroMQConfig.cmake` and got libsodium-libzmq-cppzmq setup working. You don't need to create `FindABC.cmake` module if project ABC has `ABCConfig.cmake`.

**Comment by sigiesec** [comment]
Ok, thanks for checking this again. I will close this issue then.
